name: Deploy Firebase to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: pnpm i -g firebase-tools
      - run: firebase use prod --token "${{ secrets.FIREBASE_TOKEN }}"
      - run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
