name: Run tests and deploy testing environment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Switch firebase project to test
        run: pnpm exec firebase use test --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Export environment variables to file
        run: echo "${{ secrets.ENV }}" > .env
      - name: Run unit tests
        run: pnpm exec firebase emulators:exec "pnpm run test:unit" --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Report test results
        uses: actions/github-script@v6
        with:
          script: |
            const report = require("./reports/unit.json");
            for (const file of report.testResults) {
              for (const result of file.assertionResults) {
                if (result.status === "passed") continue;
                core.warning(result.failureMessages.join("\n"), {
                  title: "AssertionError",
                  file: file.name,
                  startLine: result.location.line,
                  startColumn: result.location.column,
                });
              }
            }
        if: success() || failure()
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Switch firebase project to test
        run: pnpm exec firebase use test --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Export environment variables to file
        run: echo "${{ secrets.ENV }}" > .env
      - name: Install playwright
        run: pnpm dlx playwright install
      - name: Run e2e tests
        run: pnpm exec firebase emulators:exec "pnpm run test:e2e" --token "${{ secrets.FIREBASE_TOKEN }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract pull request ref
        run: echo "headref=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
        id: headref
      - name: Post comment
        uses: actions/github-script@v6
        env:
          GITHUB_HEAD_REF: '${{steps.headref.outputs.headref}}'
        with:
          script: |
            if (context.payload.action === "opened")
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Due to Firebase's lack of support for *deploy previews*, only one codebase can be loaded at a time in the testing environment. To bring this commit back into the testing environment, please run ```gh workflow run Firebase --ref " + process.env.GITHUB_HEAD_REF + "```",
              });
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Switch firebase project to test
        run: pnpm exec firebase use test --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Deploy to firebase
        run: pnpm exec firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
