name: Run tests and deploy testing environment

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: pnpm i
      - run: pnpm run test:unit
      - uses: actions/github-script@v6
        with:
          script: |
            const report = require("./reports/unit.json");
            for (const file of report.testResults) {
              for (const result of file.assertionResults) {
                if (result.status === "passed") continue;
                core.warning(result.failureMessages.join("\n"), {
                  title: "AssertionError",
                  file: file.name,
                  startLine: result.location.line,
                  startColumn: result.location.column,
                });
              }
            }
        if: success() || failure()
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: pnpm i
      - run: npx playwright install
      - run: pnpm run test:e2e
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "headref=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
        id: headref
      - uses: actions/github-script@v6
        env:
          GITHUB_HEAD_REF: '${{steps.headref.outputs.headref}}'
        with:
          script: |
            if (context.payload.action === "opened")
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Due to Firebase's lack of support for *deploy previews*, only one codebase can be loaded at a time in the testing environment. To bring this commit back into the testing environment, please run ```gh workflow run Firebase --ref " + process.env.GITHUB_HEAD_REF + "```",
              });
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: pnpm i -g firebase-tools
      - run: firebase use test --token "${{ secrets.FIREBASE_TOKEN }}"
      - run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
